[package]
name = "payload"
version = "0.1.0"
edition = "2024"

[dependencies]
common = {path = "../common"}

[dependencies.windows]
version = "0.60"
features = ["Win32_System_SystemServices"]

[lib]
crate-type = ["cdylib"]